### PR TITLE
Fix Commandline help for Results

### PR DESCRIPTION
**Pull request by khrm**
Fix the Commandline option for results. Added annotations to tkn results.

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Comment by rupalibehera** [comment]
cc: @chmouel could you please take a look at this one, opc results was not showing the commands correctly complete discussion (https://github.com/openshift-pipelines/opc/pull/55#issuecomment-1535974838) , then we found out that we need to add an annotation in tkn-results, so now this PR point to that version of results.

**Comment by chmouel** [comment]
we are going to need some basic smoke test for opc, because I am not sure if it actually works...

**Comment by rupalibehera** [comment]
you mean if `opc results ` work ?

**Comment by rupalibehera** [comment]
> yes,

It was working fine just not showing the commands properly, @khrm has also tested it

**Comment by rupalibehera** [comment]
thanks

**Pull request merged**
