### PR TITLE
Add activity feed API

### PR DESCRIPTION
**Pull request by khrm**

### CODE REVIEW

**Comment by khrm** [comment]
* **#147** <a href="https://app.graphite.dev/github/pr/openshift-pipelines/opc/147?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @khrm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by chmouel** [comment]
heu what is this?

**Comment by khrm** [comment]
I was playing with https://graphite.dev/ cli. It created that pr.

**Comment by chmouel** [comment]
interesting "thing"

**Pull request closed without merging**
